<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite About Gutenverse Team', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-TtJye6","background":{"videoPlayOnMobile":false,"type":"gradient","color":{"type":"variable","id":"W2b4c6"},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.468"},{"color":"rgba(237, 250, 255, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"140","right":"0","bottom":"180","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"140","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"60"}}},"zIndex":{"Tablet":"0"}} -->
<div class="section-wrapper" data-id="TtJye6"><section class="wp-block-gutenverse-section guten-element guten-section guten-TtJye6 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-rbD8oZ","horizontalAlign":{"Desktop":"flex-start","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"","right":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-rbD8oZ"><div class="guten-column-wrapper" data-id="rbD8oZ"><!-- wp:gutenverse/section {"topSticky":{"Desktop":{"point":"","unit":"px"}},"isChild":true,"gap":"no","elementId":"guten-o4wMg6","margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Desktop":[]},"padding":{"Tablet":[],"Desktop":[]},"zIndex":{"Tablet":"0","Desktop":null}} -->
<div class="section-wrapper" data-id="o4wMg6"><section class="wp-block-gutenverse-section guten-element guten-section guten-o4wMg6 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-MPPnKr","horizontalAlign":{"Desktop":"default","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"100"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"zIndex":{"Tablet":"0"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MPPnKr"><div class="guten-column-wrapper" data-id="MPPnKr"><!-- wp:gutenverse/heading {"elementId":"guten-HRxE6Z","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"background":{"type":"default","color":{"r":224,"g":234,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"11","left":"11","top":"6","bottom":"6"}},"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-HRxE6Z">Our Team</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-h8Uamz","textAlign":{"Desktop":"left","Tablet":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"bTDLqP","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"transform":"normal","spacing":{"Desktop":"-0.02"},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"10","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"511","unit":"px"}},"positioningAlign":{"Desktop":"flex-start"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-h8Uamz">Your source for financial intelligence</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-czg5Gi","alignment":{"Desktop":"left","Tablet":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":[]},"zIndex":{"Tablet":"0"},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"428","unit":"px"},"Tablet":{"point":"503","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-czg5Gi"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc nec pellentesque urna, id laoreet.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-pAvT9d","verticalAlign":{"Desktop":"flex-start"},"horizontalAlign":{"Desktop":"default","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","top":"0","bottom":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pAvT9d"><div class="guten-column-wrapper" data-id="pAvT9d"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-QGovBu"} -->
<div class="section-wrapper" data-id="QGovBu"><section class="wp-block-gutenverse-section guten-element guten-section guten-QGovBu layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-oGCzqi","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-oGCzqi"><div class="guten-column-wrapper" data-id="oGCzqi"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Go2XMg","backgroundAnimated":{"actions":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"transform":{"ease":"ease-in-out","duration":{"Desktop":null}}} -->
<div class="section-wrapper" data-id="Go2XMg"><section class="wp-block-gutenverse-section guten-element guten-section guten-Go2XMg layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-IJ4HGG","background":{"type":"default","color":{"type":"variable","id":"white"}},"backgroundAnimated":{"actions":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-IJ4HGG"><div class="guten-column-wrapper" data-id="IJ4HGG"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-bnJB12"} -->
<div class="section-wrapper" data-id="bnJB12"><section class="wp-block-gutenverse-section guten-element guten-section guten-bnJB12 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-9QOg1Y","background":{"type":"default","color":{"r":237,"g":250,"b":255,"a":1},"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"point":"15","unit":"px"}},"xposition":{"Desktop":{"point":"10","unit":"px"}},"yposition":{"Desktop":{"point":"12","unit":"px"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9QOg1Y"><div class="guten-column-wrapper" data-id="9QOg1Y"><!-- wp:gutenverse/image {"elementId":"guten-1ZSwXq","imgSrc":{"media":{"imageId":60,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_UTEZRDTKPP-1.webp","orientation":"landscape"},"medium":{"height":300,"width":202,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_UTEZRDTKPP-1.webp","orientation":"portrait"},"large":{"height":1024,"width":691,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_UTEZRDTKPP-1.webp","orientation":"portrait"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_UTEZRDTKPP-1.webp","height":1038,"width":700,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"25","right":"25","top":"20"}}},"background":{"type":"gradient","color":"","gradientType":"linear","gradientColor":[{"color":"rgba(237, 250, 255, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(183, 238, 255, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-1ZSwXq"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_UTEZRDTKPP-1.webp" height="1038" width="700" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-K9yoJa","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="K9yoJa"><section class="wp-block-gutenverse-section guten-element guten-section guten-K9yoJa layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-AMp2nB"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-AMp2nB"><div class="guten-column-wrapper" data-id="AMp2nB"><!-- wp:gutenverse/heading {"elementId":"guten-NiR0Vv","type":3,"textAlign":{"Desktop":"left","Tablet":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"39M1iD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"511","unit":"px"}},"positioningAlign":{"Desktop":"flex-start"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-NiR0Vv">James Brown</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-00s0MA","alignment":{"Desktop":"left","Tablet":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Tablet":"0"},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"428","unit":"px"},"Tablet":{"point":"503","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-00s0MA"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Chief Financial Officer</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-1H8wHA","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]},"transform":{"duration":{"Desktop":null},"ease":"ease-in-out"}} -->
<div class="section-wrapper" data-id="1H8wHA"><section class="wp-block-gutenverse-section guten-element guten-section guten-1H8wHA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-Z39cak","background":{"type":"default","color":{"type":"variable","id":"white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Z39cak"><div class="guten-column-wrapper" data-id="Z39cak"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-9LUPa8"} -->
<div class="section-wrapper" data-id="9LUPa8"><section class="wp-block-gutenverse-section guten-element guten-section guten-9LUPa8 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-sDHf4S","background":{"type":"default","color":{"r":237,"g":250,"b":255,"a":1},"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"point":"15","unit":"px"}},"xposition":{"Desktop":{"point":"10","unit":"px"}},"yposition":{"Desktop":{"point":"12","unit":"px"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sDHf4S"><div class="guten-column-wrapper" data-id="sDHf4S"><!-- wp:gutenverse/image {"elementId":"guten-VmOxIX","imgSrc":{"media":{"imageId":57,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_NHW7CBJDFM.webp","orientation":"landscape"},"medium":{"height":300,"width":202,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_NHW7CBJDFM.webp","orientation":"portrait"},"large":{"height":1024,"width":691,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_NHW7CBJDFM.webp","orientation":"portrait"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_NHW7CBJDFM.webp","height":1038,"width":700,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"25","right":"25","top":"20"}}},"background":{"type":"gradient","color":"","gradientType":"linear","gradientColor":[{"color":"rgba(237, 250, 255, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(183, 238, 255, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-VmOxIX"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_NHW7CBJDFM.webp" height="1038" width="700" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-NDDpci","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="NDDpci"><section class="wp-block-gutenverse-section guten-element guten-section guten-NDDpci layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-20EM9K"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-20EM9K"><div class="guten-column-wrapper" data-id="20EM9K"><!-- wp:gutenverse/heading {"elementId":"guten-dROHoH","type":3,"textAlign":{"Desktop":"left","Tablet":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"39M1iD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"511","unit":"px"}},"positioningAlign":{"Desktop":"flex-start"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-dROHoH">David Harrison</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-deUTU0","alignment":{"Desktop":"left","Tablet":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Tablet":"0"},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"428","unit":"px"},"Tablet":{"point":"503","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-deUTU0"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Investment Analyst</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-78GEs0","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"-90","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-78GEs0"><div class="guten-column-wrapper" data-id="78GEs0"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-K7tlJu","transform":{"duration":{"Desktop":null},"ease":"ease-in-out"}} -->
<div class="section-wrapper" data-id="K7tlJu"><section class="wp-block-gutenverse-section guten-element guten-section guten-K7tlJu layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-u97Znf","background":{"type":"default","color":{"type":"variable","id":"white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-u97Znf"><div class="guten-column-wrapper" data-id="u97Znf"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Ngx9gO"} -->
<div class="section-wrapper" data-id="Ngx9gO"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ngx9gO layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-0ygWRm","background":{"type":"default","color":{"r":237,"g":250,"b":255,"a":1},"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"point":"15","unit":"px"}},"xposition":{"Desktop":{"point":"10","unit":"px"}},"yposition":{"Desktop":{"point":"12","unit":"px"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-0ygWRm"><div class="guten-column-wrapper" data-id="0ygWRm"><!-- wp:gutenverse/image {"elementId":"guten-KpA6Kh","imgSrc":{"media":{"imageId":61,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_FPQIEQBMPA.webp","orientation":"landscape"},"medium":{"height":300,"width":202,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_FPQIEQBMPA.webp","orientation":"portrait"},"large":{"height":1024,"width":691,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_FPQIEQBMPA.webp","orientation":"portrait"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_FPQIEQBMPA.webp","height":1038,"width":700,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"25","right":"25","top":"20"}}},"background":{"type":"gradient","color":"","gradientType":"linear","gradientColor":[{"color":"rgba(237, 250, 255, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(183, 238, 255, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-KpA6Kh"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_FPQIEQBMPA.webp" height="1038" width="700" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-CxHQC8","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="CxHQC8"><section class="wp-block-gutenverse-section guten-element guten-section guten-CxHQC8 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-ergBwa"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ergBwa"><div class="guten-column-wrapper" data-id="ergBwa"><!-- wp:gutenverse/heading {"elementId":"guten-fVoN86","type":3,"textAlign":{"Desktop":"left","Tablet":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"39M1iD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"511","unit":"px"}},"positioningAlign":{"Desktop":"flex-start"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-fVoN86">Linda Dou</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-YWUo2F","alignment":{"Desktop":"left","Tablet":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Tablet":"0"},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"428","unit":"px"},"Tablet":{"point":"503","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-YWUo2F"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Finance Director</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-LS3oDl","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]},"transform":{"ease":"ease-in-out","delay":{"Desktop":null},"duration":{"Desktop":null}}} -->
<div class="section-wrapper" data-id="LS3oDl"><section class="wp-block-gutenverse-section guten-element guten-section guten-LS3oDl layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-vWLtc1","background":{"type":"default","color":{"type":"variable","id":"white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vWLtc1"><div class="guten-column-wrapper" data-id="vWLtc1"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-oMI3fB"} -->
<div class="section-wrapper" data-id="oMI3fB"><section class="wp-block-gutenverse-section guten-element guten-section guten-oMI3fB layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-pz5yXx","background":{"type":"default","color":{"r":237,"g":250,"b":255,"a":1},"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom"},"width":{"Desktop":{"point":"15","unit":"px"}},"xposition":{"Desktop":{"point":"10","unit":"px"}},"yposition":{"Desktop":{"point":"12","unit":"px"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pz5yXx"><div class="guten-column-wrapper" data-id="pz5yXx"><!-- wp:gutenverse/image {"elementId":"guten-2Lmmmw","imgSrc":{"media":{"imageId":62,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_XP4VUP0LGW.webp","orientation":"landscape"},"medium":{"height":300,"width":202,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_XP4VUP0LGW.webp","orientation":"portrait"},"large":{"height":1024,"width":691,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_XP4VUP0LGW.webp","orientation":"portrait"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_XP4VUP0LGW.webp","height":1038,"width":700,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"25","right":"25","top":"20"}}},"background":{"type":"gradient","color":"","gradientType":"linear","gradientColor":[{"color":"rgba(237, 250, 255, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(183, 238, 255, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-2Lmmmw"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_XP4VUP0LGW.webp" height="1038" width="700" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-lCOAzf","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="lCOAzf"><section class="wp-block-gutenverse-section guten-element guten-section guten-lCOAzf layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-xy01qq"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xy01qq"><div class="guten-column-wrapper" data-id="xy01qq"><!-- wp:gutenverse/heading {"elementId":"guten-1OU6Fh","type":3,"textAlign":{"Desktop":"left","Tablet":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"39M1iD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"511","unit":"px"}},"positioningAlign":{"Desktop":"flex-start"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-1OU6Fh">Sarah Baker</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-sYmTcC","alignment":{"Desktop":"left","Tablet":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Tablet":"0"},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"point":"428","unit":"px"},"Tablet":{"point":"503","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-sYmTcC"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Financial Planner</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
