<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Page Gutenverse Hero', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"height":{"Desktop":{"point":"628.38","unit":"px"}},"gap":"no","elementId":"guten-eoYoiB","background":{"type":"default","videoPlayOnMobile":false,"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"yposition":{"Desktop":{"point":"15","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0.8)","active":true,"opacity":0.8,"id":3,"offset":"0.558"},{"color":"rgba(237, 250, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"topDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"loop":true,"width":{"Desktop":"154"},"height":{"Desktop":"490"}},"bottomDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"width":{"Desktop":"200"},"flip":false,"front":false,"loop":false},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"130","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"110","right":"30","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"20","bottom":"0","left":"20"}}},"zIndex":{"Desktop":"3"},"condition":{"filter":[]}} -->
<div class="section-wrapper" data-id="eoYoiB"><section class="wp-block-gutenverse-section guten-element guten-section guten-eoYoiB layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-ZaB07F","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ZaB07F"><div class="guten-column-wrapper" data-id="ZaB07F"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-YCi2iy","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"20","right":"20"}}}},"boxShadow":{"horizontal":"0","vertical":"3","blur":"30","spread":"4","position":"outline","color":{"r":83,"g":180,"b":252,"a":0.1}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"-90"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-80","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"-45","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="YCi2iy"><section class="wp-block-gutenverse-section guten-element guten-section guten-YCi2iy layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-S8OtXV","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-S8OtXV"><div class="guten-column-wrapper" data-id="S8OtXV"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"150","unit":"px"}},"gap":"no","elementId":"guten-aXDqs5","verticalAlign":"flex-end","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20"}}},"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"right":{"color":{"type":"variable","id":"theme-7"},"type":"solid","width":"1"},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}}} -->
<div class="section-wrapper" data-id="aXDqs5"><section class="wp-block-gutenverse-section guten-element guten-section guten-aXDqs5 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"flex-end","elementId":"guten-qi7IKI","verticalAlign":{"Desktop":"default","Tablet":"center"},"horizontalAlign":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qi7IKI"><div class="guten-column-wrapper" data-id="qi7IKI"><!-- wp:gutenverse/post-title {"elementId":"guten-LpxgI2","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"ROsdhu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"64","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.02"}}} -->
<div class="guten-element guten-post-title guten-LpxgI2"></div>
<!-- /wp:gutenverse/post-title --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-gJXHok","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":6,"g":6,"b":6,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"0","right":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"18","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="gJXHok"><section class="wp-block-gutenverse-section guten-element guten-section guten-gJXHok layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-MyofRT","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"18","right":"0","bottom":"18","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MyofRT"><div class="guten-column-wrapper" data-id="MyofRT"><!-- wp:gutenverse/spacer {"elementId":"guten-9V9H1G","space":{"Desktop":{"point":"12","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-9V9H1G"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
