<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Home Gutenverse About', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-YgNUTF","background":{"type":"default","videoPlayOnMobile":false,"gradientColor":[{"color":"rgba(244, 251, 255, 1)","opacity":1,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.976"}],"gradientType":"linear","image":{"Desktop":{"id":3327,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.png"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"21","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"xposition":{"Desktop":{"point":"0","unit":"px"}},"yposition":{"Desktop":{"point":"15","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"top":{"type":"none","color":{"type":"variable","id":"YUPZJz"},"width":"3"}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"240","bottom":"120","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"190","right":"30","bottom":"60","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"190","right":"20","bottom":"40","left":"20"}}}} -->
<div class="section-wrapper" data-id="YgNUTF"><section class="wp-block-gutenverse-section guten-element guten-section guten-YgNUTF layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":40,"Tablet":40,"Mobile":100},"elementId":"guten-VPUsiB","verticalAlign":{"Desktop":"space-between","Tablet":"space-between"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VPUsiB"><div class="guten-column-wrapper" data-id="VPUsiB"><!-- wp:gutenverse/heading {"elementId":"guten-43JD0m","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"background":{"type":"default","color":{"r":224,"g":234,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"11","left":"11","top":"6","bottom":"6"}},"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-43JD0m">Who we Are</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-qWJl0c","alignment":{"Desktop":"left","Tablet":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hideMobile":true,"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"200","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-qWJl0c hide-mobile"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Personalized wealth management</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":60,"Tablet":60,"Mobile":100},"elementId":"guten-fwpIwT","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fwpIwT"><div class="guten-column-wrapper" data-id="fwpIwT"><!-- wp:gutenverse/heading {"elementId":"guten-BdcCRu","textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"bTDLqP","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"transform":"normal","spacing":{"Desktop":"-0.02"},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"30","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"13","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Tablet":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"470","unit":"px"},"Mobile":{"point":"318","unit":"px"}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-BdcCRu">Tailored strategies for financial success</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-1yEfNL","columns":{"Desktop":""},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"12","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"835","unit":"px"},"Mobile":{"point":"435","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Tablet":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-1yEfNL"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Etiam a mi ante. Etiam at quam sapien. Integer maximus fringilla nibh, id sagittis massad efficitur nec. Mauris ornare venenatis nulla, nec tincidunt lectus sagittis idete.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-APh1jS","columns":{"Desktop":""},"alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"835","unit":"px"},"Mobile":{"point":"435","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Tablet":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-APh1jS"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam augue dolor, rumedeted vitae laoreet eget, auctor et urna. Duis elementum enim nequtiam attem mi antetiame at quam sapien. Integer maximus fringilla nibh, id sagittis sedut seduted massa sedue efficitur nec. Mauris ornare venenatis nulla, nec tincidunt lectussed.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-R7dzOI","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":"35"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"05","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]}} -->
<div class="section-wrapper" data-id="R7dzOI"><section class="wp-block-gutenverse-section guten-element guten-section guten-R7dzOI layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":100,"Tablet":null},"sectionVerticalAlign":"center","elementId":"guten-b9DKw9"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-b9DKw9"><div class="guten-column-wrapper" data-id="b9DKw9"><!-- wp:gutenverse/heading {"elementId":"guten-E938bD","type":4,"color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"b65SN7","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"400","transform":"normal"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-4"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"14","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"12","left":"12","top":"8","bottom":"8"}}},"hideMobile":true,"positioningType":{"Desktop":"inline"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-E938bD hide-mobile">Business</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-ZMnDGF","type":4,"color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"b65SN7","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"400","transform":"normal"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-4"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"14","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"12","left":"12","top":"8","bottom":"8"}},"Mobile":[]},"positioningType":{"Desktop":"inline"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-ZMnDGF">Tax Plan</h4>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-rlt0J9","type":4,"color":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"b65SN7","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"400","transform":"normal"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-4"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"12","left":"12","top":"8","bottom":"8"}}},"positioningType":{"Desktop":"inline"}} -->
<h4 class="wp-block-gutenverse-heading guten-element guten-rlt0J9">Budgeting</h4>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
