<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Gutenverse Client Logo', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1440"},"height":{"Desktop":{"point":"150","unit":"px"},"Mobile":{"point":"","unit":"px"}},"gap":"no","elementId":"guten-lvIXP3","heightControl":"min","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50","left":"50"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="lvIXP3"><section class="wp-block-gutenverse-section guten-element guten-section guten-lvIXP3 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-eC5H4t","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"none","width":"1","color":{"type":"variable","id":"bZzZn0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eC5H4t"><div class="guten-column-wrapper" data-id="eC5H4t"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"height":{"Desktop":{"point":"160","unit":"px"},"Tablet":{"point":"210","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"gap":"no","elementId":"guten-yWPTZ4","heightControl":"min","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="yWPTZ4"><section class="wp-block-gutenverse-section guten-element guten-section guten-yWPTZ4 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":16.6,"Tablet":33.3,"Mobile":50},"elementId":"guten-1zzqp0","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"left":{"type":"none","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Mobile":{"radius":[],"right":{"type":"solid"},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"Tablet":{"radius":[]}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1zzqp0"><div class="guten-column-wrapper" data-id="1zzqp0"><!-- wp:gutenverse/image {"elementId":"guten-UajuUy","imgSrc":{"media":{"imageId":312,"sizes":{"thumbnail":{"height":74,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-6.webp","orientation":"landscape"},"medium":{"height":50,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-6.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-6.webp","height":74,"width":440,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"135","unit":"px"},"Tablet":{"point":"125","unit":"px"},"Mobile":{"point":"90","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"opacity":"0.9"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-UajuUy"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-6.webp" height="74" width="440"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.6,"Tablet":33.3,"Mobile":50},"elementId":"guten-fJnmF2","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Mobile":{"radius":[],"right":{"type":"none"},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fJnmF2"><div class="guten-column-wrapper" data-id="fJnmF2"><!-- wp:gutenverse/image {"elementId":"guten-mu16Oe","imgSrc":{"media":{"imageId":50,"sizes":{"thumbnail":{"height":62,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-1.webp","orientation":"landscape"},"medium":{"height":45,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-1.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-1.webp","height":62,"width":416,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"135","unit":"px"},"Tablet":{"point":"125","unit":"px"},"Mobile":{"point":"90","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"opacity":"0.9"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-mu16Oe"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-1.webp" height="62" width="416"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.6,"Tablet":33.3,"Mobile":50},"elementId":"guten-6riGrT","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Tablet":{"radius":[],"right":{"type":"none"}},"Mobile":{"radius":[],"right":{"type":"solid"}}},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6riGrT"><div class="guten-column-wrapper" data-id="6riGrT"><!-- wp:gutenverse/image {"elementId":"guten-atLECe","imgSrc":{"media":{"imageId":49,"sizes":{"thumbnail":{"height":62,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-2.webp","orientation":"landscape"},"medium":{"height":46,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-2.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-2.webp","height":62,"width":402,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"135","unit":"px"},"Tablet":{"point":"125","unit":"px"},"Mobile":{"point":"90","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"opacity":"0.9"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-atLECe"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-2.webp" height="62" width="402"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.6,"Tablet":33.3,"Mobile":50},"elementId":"guten-gr846n","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Tablet":{"radius":[],"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"Mobile":{"radius":[],"right":{"type":"none"},"top":{"type":"none"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-gr846n"><div class="guten-column-wrapper" data-id="gr846n"><!-- wp:gutenverse/image {"elementId":"guten-GuIexj","imgSrc":{"media":{"imageId":47,"sizes":{"thumbnail":{"height":62,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-4.webp","orientation":"landscape"},"medium":{"height":51,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-4.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-4.webp","height":62,"width":364,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"125","unit":"px"},"Tablet":{"point":"125","unit":"px"},"Mobile":{"point":"90","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"opacity":"0.9"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-GuIexj"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-4.webp" height="62" width="364"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.6,"Tablet":33.3,"Mobile":null},"elementId":"guten-cv0xRX","verticalAlign":{"Desktop":"center","Tablet":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Tablet":{"radius":[],"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"Mobile":{"radius":[]}},"borderHover":{"radius":{"Desktop":[]}},"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cv0xRX hide-mobile"><div class="guten-column-wrapper" data-id="cv0xRX"><!-- wp:gutenverse/image {"elementId":"guten-49IpsG","imgSrc":{"media":{"imageId":48,"sizes":{"thumbnail":{"height":136,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-3.webp","orientation":"landscape"},"medium":{"height":41,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-3.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-3.webp","height":136,"width":998,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"155","unit":"px"},"Tablet":{"point":"125","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]}},"align":{"Desktop":"center"},"opacity":"0.9"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-49IpsG"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-3.webp" height="136" width="998"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":16.6,"Tablet":33.3,"Mobile":null},"elementId":"guten-U2FGEJ","verticalAlign":{"Desktop":"center","Tablet":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"none","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Tablet":{"radius":[],"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"Mobile":{"radius":[]}},"hideTablet":false,"hideMobile":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-U2FGEJ hide-mobile"><div class="guten-column-wrapper" data-id="U2FGEJ"><!-- wp:gutenverse/image {"elementId":"guten-CFAeJc","imgSrc":{"media":{"imageId":46,"sizes":{"thumbnail":{"height":63,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-5.webp","orientation":"landscape"},"medium":{"height":53,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-5.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-5.webp","height":63,"width":360,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","width":{"Desktop":{"point":"135","unit":"px"},"Tablet":{"point":"125","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]}},"align":{"Desktop":"center"},"opacity":"0.9"} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-CFAeJc"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/client-logo-5.webp" height="63" width="360"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
