<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Single Gutenverse Hero', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"900"},"height":{"Desktop":{"point":"628.38","unit":"px"}},"gap":"no","elementId":"guten-0aKU1Q","background":{"type":"default","videoPlayOnMobile":false,"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"yposition":{"Desktop":{"point":"15","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0.8)","active":true,"opacity":0.8,"id":3,"offset":"0.558"},{"color":"rgba(237, 250, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"topDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"loop":true,"width":{"Desktop":"154"},"height":{"Desktop":"490"}},"bottomDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"width":{"Desktop":"200"},"flip":false,"front":false,"loop":false},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"110","right":"30","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"20","bottom":"0","left":"20"}}},"zIndex":{"Desktop":"3"},"condition":{"filter":[]}} -->
<div class="section-wrapper" data-id="0aKU1Q"><section class="wp-block-gutenverse-section guten-element guten-section guten-0aKU1Q layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-e0GnlM","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-e0GnlM"><div class="guten-column-wrapper" data-id="e0GnlM"><!-- wp:gutenverse/section {"width":{"Desktop":"900"},"isChild":true,"gap":"no","elementId":"guten-y6015C","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"50","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"condition":{"filter":[]}} -->
<div class="section-wrapper" data-id="y6015C"><section class="wp-block-gutenverse-section guten-element guten-section guten-y6015C layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-YY9WAc","verticalAlign":{"Desktop":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YY9WAc"><div class="guten-column-wrapper" data-id="YY9WAc"><!-- wp:gutenverse/post-terms {"elementId":"guten-c8M0SH","linkTo":"term","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"color":{"type":"variable","id":"theme-3"},"background":{"type":"default","color":{"type":"variable","id":"theme-7"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"11","bottom":"4","left":"11"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-terms guten-c8M0SH"></div>
<!-- /wp:gutenverse/post-terms -->

<!-- wp:gutenverse/post-title {"elementId":"guten-9HRm3U","postLink":false,"postLinkTarget":false,"alignment":{"Desktop":"center","Mobile":"flex-start"},"typography":{"type":"variable","id":"ROsdhu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"64","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.02"}},"color":{"type":"variable","id":"theme-0"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"945","unit":"px"}}} -->
<div class="guten-element guten-post-title guten-9HRm3U"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/post-author {"elementId":"guten-ji7XdS","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"color":{"type":"variable","id":"theme-0"},"authorBorder":{"radius":{"Desktop":[]}},"authorBorderResponsive":{"Desktop":{"radius":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"2","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"inline","Mobile":"inline"}} -->
<div class="guten-element guten-post-author guten-ji7XdS"></div>
<!-- /wp:gutenverse/post-author -->

<!-- wp:gutenverse/icon {"elementId":"guten-mLResU","icon":"fas fa-minus","iconAlign":{"Desktop":"left"},"iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"12","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"theme-2"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-mLResU guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="fas fa-minus"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/post-date {"elementId":"guten-zSLN5u","alignment":{"Desktop":"flex-start"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"color":{"type":"variable","id":"theme-2"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-date guten-zSLN5u"></div>
<!-- /wp:gutenverse/post-date --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"367","unit":"px"}},"gap":"no","elementId":"guten-jKIyTu","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"20","right":"20"}}}},"boxShadow":{"horizontal":"0","vertical":"3","blur":"30","spread":"4","position":"outline","color":{"r":83,"g":180,"b":252,"a":0.1}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"-200"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-80","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"-45","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="jKIyTu"><section class="wp-block-gutenverse-section guten-element guten-section guten-jKIyTu layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-RQNuLl","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RQNuLl"><div class="guten-column-wrapper" data-id="RQNuLl"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"58","unit":"px"}},"gap":"no","elementId":"guten-ArjPbO","verticalAlign":"flex-end","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20"}}}},"borderResponsive":{"Tablet":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="ArjPbO"><section class="wp-block-gutenverse-section guten-element guten-section guten-ArjPbO layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"flex-end","elementId":"guten-Coz0cL","verticalAlign":{"Desktop":"default","Tablet":"center"},"horizontalAlign":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Coz0cL"><div class="guten-column-wrapper" data-id="Coz0cL"><!-- wp:gutenverse/post-featured-image {"elementId":"guten-TrPres","alignment":{"Desktop":null},"size":{"Desktop":{"point":"","unit":"px"}},"opacity":{"Desktop":""},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"0","left":"0"}}}},"imageBorderResponsive":{"Tablet":{"radius":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element guten-post-featured-image guten-TrPres"></div>
<!-- /wp:gutenverse/post-featured-image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-KDH6lf","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":6,"g":6,"b":6,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"0","right":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"18","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="KDH6lf"><section class="wp-block-gutenverse-section guten-element guten-section guten-KDH6lf layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-EzYEda","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"18","right":"0","bottom":"18","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-EzYEda"><div class="guten-column-wrapper" data-id="EzYEda"><!-- wp:gutenverse/text-editor {"elementId":"guten-LOn1Yz","gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}}},"positioningType":{"Desktop":"default","Tablet":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"334","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-LOn1Yz"><div class="text-content-inner"><!-- wp:paragraph -->
<p>*Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
