<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Service Gutenverse Funfact', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-TK98Dh","background":{"videoPlayOnMobile":false,"type":"gradient","color":{"type":"variable","id":"W2b4c6"},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.468"},{"color":"rgba(237, 250, 255, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"opacity":"0","border":{"radius":{"Desktop":[]},"top":{"type":"solid","width":"0","color":{"type":"variable","id":"YUPZJz"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","right":"0","bottom":"180","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"120","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"60"}}},"zIndex":{"Tablet":"0"}} -->
<div class="section-wrapper" data-id="TK98Dh"><section class="wp-block-gutenverse-section guten-element guten-section guten-TK98Dh layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"elementId":"guten-KRbyZI","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KRbyZI"><div class="guten-column-wrapper" data-id="KRbyZI"><!-- wp:gutenverse/section {"width":{"Desktop":"1000"},"isChild":true,"gap":"no","elementId":"guten-Ipc4vq","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"70","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="Ipc4vq"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ipc4vq layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":33,"Mobile":50},"elementId":"guten-9sgEDv","border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[],"right":{"type":"none"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9sgEDv"><div class="guten-column-wrapper" data-id="9sgEDv"><!-- wp:gutenverse/fun-fact {"elementId":"guten-NgNsv2","icon":"","iconBorder":{"radius":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"90","suffix":"%","title":"Profit Growth","numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]}}} -->
<div class="guten-element guten-NgNsv2 guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="90" data-duration="3500"></span><span class="suffix">%</span></div><span class="title">Profit Growth</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":"33","Mobile":50},"elementId":"guten-sWVjeg"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sWVjeg"><div class="guten-column-wrapper" data-id="sWVjeg"><!-- wp:gutenverse/fun-fact {"elementId":"guten-ebak84","icon":"","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"24/7","suffix":"","title":"Customer Care","numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[]}} -->
<div class="guten-element guten-ebak84 guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="24/7" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Customer Care</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-t54STm","horizontalAlign":{"Desktop":"default","Mobile":"default"},"border":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"hideTablet":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-t54STm hide-tablet"><div class="guten-column-wrapper" data-id="t54STm"><!-- wp:gutenverse/fun-fact {"elementId":"guten-tIV5On","icon":"","iconColor":{"Mobile":{"type":"variable","id":"CioHMV"}},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"130","suffix":"+","title":"Trusted by Companies","alignButtons":{"Desktop":"center"},"numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]}} -->
<div class="guten-element guten-tIV5On guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="130" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Trusted by Companies</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":"33","Mobile":50},"elementId":"guten-NG8wkW","border":{"radius":{"Desktop":[]}},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NG8wkW"><div class="guten-column-wrapper" data-id="NG8wkW"><!-- wp:gutenverse/fun-fact {"elementId":"guten-aklm3u","icon":"","iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"15","suffix":"K","title":"Happy Client","numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]}} -->
<div class="guten-element guten-aklm3u guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="15" data-duration="3500"></span><span class="suffix">K</span></div><span class="title">Happy Client</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
