<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite 404 Gutenverse Hero', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"height":{"Desktop":{"point":"628.38","unit":"px"}},"gap":"no","elementId":"guten-nFGA4t","background":{"type":"default","videoPlayOnMobile":false,"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"yposition":{"Desktop":{"point":"15","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0.8)","active":true,"opacity":0.8,"id":3,"offset":"0.558"},{"color":"rgba(237, 250, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"topDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"loop":true,"width":{"Desktop":"154"},"height":{"Desktop":"490"}},"bottomDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"width":{"Desktop":"200"},"flip":false,"front":false,"loop":false},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"180","bottom":"230"}},"Tablet":{"unit":"px","dimension":{"top":"110","right":"30","bottom":"220","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"20","bottom":"170","left":"20"}}},"zIndex":{"Desktop":0},"condition":{"filter":[]}} -->
<div class="section-wrapper" data-id="nFGA4t"><section class="wp-block-gutenverse-section guten-element guten-section guten-nFGA4t layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-dEdb91","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-dEdb91"><div class="guten-column-wrapper" data-id="dEdb91"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-pfYosA","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"20","right":"20"}}}},"boxShadow":{"horizontal":"0","vertical":"3","blur":"30","spread":"4","position":"outline","color":{"r":83,"g":180,"b":252,"a":0.1}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-80","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"-45","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="pfYosA"><section class="wp-block-gutenverse-section guten-element guten-section guten-pfYosA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-3qTwp3","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3qTwp3"><div class="guten-column-wrapper" data-id="3qTwp3"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"150","unit":"px"}},"gap":"no","elementId":"guten-AhEmnX","verticalAlign":"center","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20"}}},"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"right":{"color":{"type":"variable","id":"theme-7"},"type":"solid","width":"1"},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"30","left":"20"}}}} -->
<div class="section-wrapper" data-id="AhEmnX"><section class="wp-block-gutenverse-section guten-element guten-section guten-AhEmnX layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":57,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-P58RBD","order":{"Tablet":1,"Mobile":2},"verticalAlign":{"Desktop":"default","Tablet":"center"},"horizontalAlign":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-P58RBD"><div class="guten-column-wrapper" data-id="P58RBD"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-I3Ab2z","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="section-wrapper" data-id="I3Ab2z"><section class="wp-block-gutenverse-section guten-element guten-section guten-I3Ab2z layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-fKkBmF","horizontalAlign":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fKkBmF"><div class="guten-column-wrapper" data-id="fKkBmF"><!-- wp:gutenverse/heading {"elementId":"guten-Gw9HbF","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"background":{"type":"default","color":{"r":224,"g":234,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"15","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"11","left":"11","top":"6","bottom":"6"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-Gw9HbF">oops</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-DZ5sOv","alignment":{"Desktop":"left","Tablet":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hideMobile":true,"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element gutenverse-text-editor guten-DZ5sOv hide-mobile"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-n4SIkr","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"70","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]}} -->
<div class="section-wrapper" data-id="n4SIkr"><section class="wp-block-gutenverse-section guten-element guten-section guten-n4SIkr layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-FSkpvn","horizontalAlign":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-FSkpvn"><div class="guten-column-wrapper" data-id="FSkpvn"><!-- wp:gutenverse/heading {"elementId":"guten-rLzDiH","type":1,"textAlign":{"Desktop":"left","Tablet":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"ROsdhu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"64","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","right":"","top":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"15","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"630"},"Tablet":{"point":"638","unit":"px"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-rLzDiH">We’ve lost this page</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Nf0ZSa","gap":{"Tablet":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Tablet":"left","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Desktop":[]},"hideDesktop":false,"hideTablet":true,"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"450","unit":"px"},"Tablet":{"point":"415","unit":"px"},"Mobile":{"point":"289","unit":"px"}},"positioningAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="guten-element gutenverse-text-editor guten-Nf0ZSa hide-tablet"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Aliquam quam liquam loremsed, congue eget odio sit amet, ultricies imperdiet metusmi congue eget.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/button {"elementId":"guten-l5u6ZZ","content":"Back to home","alignButton":{"Desktop":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"13","right":"27","bottom":"13","left":"27"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"8"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"6"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"hoverTextColor":{"type":"variable","id":"W2b4c6"},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element guten-button-wrapper guten-l5u6ZZ"><a class="guten-button guten-button-sm" href="#"><span>Back to home</span></a></div>
<!-- /wp:gutenverse/button -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-3gMHtZ","gap":{"Tablet":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Tablet":"left","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"NumcB8","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"12","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"6","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Desktop":[]},"hideDesktop":false,"hideTablet":true,"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"501","unit":"px"},"Tablet":{"point":"566","unit":"px"},"Mobile":{"point":"289","unit":"px"}},"positioningAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="guten-element gutenverse-text-editor guten-3gMHtZ hide-tablet"><div class="text-content-inner"><!-- wp:paragraph -->
<p>*Aliquam quam liquam lorem</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":43,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-r7pFI0","order":{"Tablet":2,"Mobile":1},"verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"borderResponsive":{"Tablet":{"radius":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"25","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-r7pFI0"><div class="guten-column-wrapper" data-id="r7pFI0"><!-- wp:gutenverse/section {"width":{"Desktop":"1380"},"isChild":true,"height":{"Desktop":{"point":"530","unit":"px"}},"gap":"no","elementId":"guten-Rd9457","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"advanceAnimation":{"actions":[],"smoothness":"2","anchor":"","pin":false},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"1200","unit":"px"}}} -->
<div class="section-wrapper" data-id="Rd9457"><section class="wp-block-gutenverse-section guten-element guten-section guten-Rd9457 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-lzUo1o","background":{"type":"gradient","gradientColor":[{"color":"rgba(64, 182, 253, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(32, 104, 245, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"opacity":"0.1","backgroundAnimated":{"actions":[]},"verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"flex-start"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"borderResponsive":{"Tablet":{"radius":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"20","top":"20"}}},"Mobile":{"radius":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"boxShadow":{"vertical":"10","blur":"40","spread":"-10","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","bottom":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mouseMoveEffect":{"enable":false},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"Detail","textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"background":{"type":"default","color":{"type":"variable","id":"white"},"fixed":{"Desktop":false},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(220, 246, 255, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear"},"textColor":{"type":"variable","id":"YUPZJz"},"delay":true,"defaultSpeed":{"point":"0.05","unit":"s"},"disableDefault":true,"padding":{"unit":"px","dimension":{"top":"40","right":"25","bottom":"40","left":"25"}},"typography":{"type":"variable","id":"gqDfIO","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Mobile":{"unit":"em","point":"1.1"}}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lzUo1o"><div class="guten-column-wrapper" data-id="lzUo1o"><!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-xFv8aP","verticalAlign":"center","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"45","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"25","left":"25","bottom":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"30","left":"30"}}}} -->
<div class="section-wrapper" data-id="xFv8aP"><section class="wp-block-gutenverse-section guten-element guten-section guten-xFv8aP layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-RYt5DC","margin":{"Mobile":[]},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-RYt5DC"><div class="guten-column-wrapper" data-id="RYt5DC"><!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-2VHafu","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":191,"g":29,"b":29,"a":0}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="2VHafu"><section class="wp-block-gutenverse-section guten-element guten-section guten-2VHafu layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-K5F77v","horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-K5F77v"><div class="guten-column-wrapper" data-id="K5F77v"><!-- wp:gutenverse/heading {"elementId":"guten-LbDGJ3","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"background":{"type":"default","color":{"r":255,"g":196,"b":1,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"18","left":"18","top":"7","bottom":"8"}},"Mobile":[],"Tablet":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"},"positioningLocation":"default","positioningLeft":{"Desktop":{"point":"225","unit":"px"},"Tablet":{"point":"209","unit":"px"},"Mobile":{"point":"150","unit":"px"}},"positioningTop":{"Desktop":{"point":"-56","unit":"px"},"Tablet":{"point":"-48","unit":"px"},"Mobile":{"point":"-30","unit":"px"}},"positioningBottom":{"Mobile":{"point":"","unit":"px"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-LbDGJ3">Error</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-kVV9co","type":1,"textAlign":{"Desktop":"left","Mobile":"left"},"color":{"type":"variable","id":"white"},"typography":{"font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"88","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"transform":"capitalize","spacing":{"Desktop":"-0.01"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"25","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"12","right":"0","bottom":"14","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"30","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"265","unit":"px"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-kVV9co">404</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-NFyFII","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"left"},"textColor":{"r":255,"g":255,"b":255,"a":0.7},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-5","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"positioningType":{"Desktop":"custom","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-NFyFII"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames aante ipsum primis in faucibused. </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-7VOb0l","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":6,"g":6,"b":6,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"0","right":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"18","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="7VOb0l"><section class="wp-block-gutenverse-section guten-element guten-section guten-7VOb0l layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-MyIest","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"18","right":"0","bottom":"18","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MyIest"><div class="guten-column-wrapper" data-id="MyIest"><!-- wp:gutenverse/text-editor {"elementId":"guten-cVgd7a","gap":{"Desktop":{"point":"","unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}}},"positioningType":{"Desktop":"default","Tablet":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"334","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-cVgd7a"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
