<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Home Gutenverse Hero', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"height":{"Desktop":{"point":"628.38","unit":"px"}},"gap":"no","elementId":"guten-OgaXvO","background":{"type":"default","videoPlayOnMobile":false,"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"yposition":{"Desktop":{"point":"15","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"topDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"loop":true,"width":{"Desktop":"154"},"height":{"Desktop":"490"}},"bottomDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"width":{"Desktop":"200"},"flip":false,"front":false,"loop":false},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"180","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"140","right":"30","bottom":"70","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"70","left":"20"}}},"zIndex":{"Desktop":"3"},"condition":{"filter":[]}} -->
<div class="section-wrapper" data-id="OgaXvO"><section class="wp-block-gutenverse-section guten-element guten-section guten-OgaXvO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-bNYNAj","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-bNYNAj"><div class="guten-column-wrapper" data-id="bNYNAj"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Mobile":"890"},"isChild":true,"gap":"no","elementId":"guten-hRcSRd"} -->
<div class="section-wrapper" data-id="hRcSRd"><section class="wp-block-gutenverse-section guten-element guten-section guten-hRcSRd layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-aDzhMG","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"condition":{"filter":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-aDzhMG"><div class="guten-column-wrapper" data-id="aDzhMG"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-pT7xal","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="section-wrapper" data-id="pT7xal"><section class="wp-block-gutenverse-section guten-element guten-section guten-pT7xal layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-epD0ZL","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-epD0ZL"><div class="guten-column-wrapper" data-id="epD0ZL"><!-- wp:gutenverse/heading {"elementId":"guten-DzsJQ4","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"background":{"type":"default","color":{"type":"variable","id":"theme-7"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"15","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"11","left":"11","top":"6","bottom":"6"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-DzsJQ4">New</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Dos4wD","alignment":{"Desktop":"left","Tablet":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hideMobile":true,"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element gutenverse-text-editor guten-Dos4wD hide-mobile"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Your Trusted Financial Partner</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/heading {"elementId":"guten-kRB4jk","type":1,"textAlign":{"Desktop":"center","Tablet":"center"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"Djl5py","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"120","unit":"px"},"Tablet":{"point":"88","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"transform":"uppercase","spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"5","right":""}},"Mobile":{"unit":"px","dimension":{"bottom":"15","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":[]},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"1000"},"Tablet":{"point":"638","unit":"px"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-kRB4jk">Precision Planning for Financial Success</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-DXY2Mq","gap":{"Tablet":{"point":"","unit":"px"}},"alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"844OpL","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10","top":"-10","bottom":"0"}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}},"Desktop":[]},"hideDesktop":false,"hideTablet":false,"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"762","unit":"px"},"Tablet":{"point":"446","unit":"px"},"Mobile":{"point":"289","unit":"px"}},"positioningAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="guten-element gutenverse-text-editor guten-DXY2Mq"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Rhoncus arcu risus, vel finibus arcunc augue libero.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-Tk8Oxk","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="section-wrapper" data-id="Tk8Oxk"><section class="wp-block-gutenverse-section guten-element guten-section guten-Tk8Oxk layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-7KnmCU","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-7KnmCU"><div class="guten-column-wrapper" data-id="7KnmCU"><!-- wp:gutenverse/button {"elementId":"guten-z3Zabn","content":"Get Started","alignButton":{"Tablet":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"25","bottom":"20","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"25","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"20","bottom":"15","left":"20"}}},"buttonBackground":{"type":"default","gradientColor":[{"color":"rgba(32, 104, 245, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(64, 182, 253, 1)","active":false,"opacity":1,"id":2,"offset":"0.951"}],"gradientType":"linear","gradientAngle":"0","gradientRadial":"bottom center","color":{"type":"variable","id":"theme-3"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"},"gradientType":"linear","gradientColor":[{"color":"rgba(51, 116, 245, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(64, 182, 253, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientAngle":"0"},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"buttonBorderResponsive":{"Tablet":{"radius":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}}},"Mobile":{"radius":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"buttonBorderHoverResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"12","Mobile":"12"},"iconSize":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}},"Tablet":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Desktop":"4"},"color":{"type":"variable","id":"white"},"iconColor":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"bewSkj","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"600"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-z3Zabn"><a class="guten-button guten-button-sm" href="#"><span>Get Started</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"height":{"Desktop":{"point":"600","unit":"px"}},"gap":"no","elementId":"guten-vTELGA","background":{"videoPlayOnMobile":false,"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(237, 250, 255, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","color":{"r":237,"g":250,"b":255,"a":1},"gradientAngle":"180"},"border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"0","color":{"type":"variable","id":"YUPZJz"}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50","left":"50","top":"100"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"zIndex":{"Tablet":"2","Desktop":"2"},"hideDesktop":false,"advanceAnimation":{"actions":[{"type":"scale","ease":"power1.inOut","timeline":{"start":0,"end":"50","unit":"%"},"scaleXFrom":{"point":"0.7","unit":"px"},"scaleYFrom":{"point":"0.7","unit":"px"},"scaleXTo":{"point":"1.2","unit":"px"},"scaleYTo":{"point":"1.2","unit":"px"}}],"smoothness":"2"}} -->
<div class="section-wrapper" data-id="vTELGA"><section class="wp-block-gutenverse-section guten-element guten-section guten-vTELGA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-oqLnAO","background":{"type":"default","image":{"Desktop":{"id":12,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_EDZW9PBAZX.webp"}},"position":{"Desktop":"custom","Mobile":"center center"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"yposition":{"Desktop":{"unit":"%","point":"23"}}},"backgroundAnimated":{"actions":[],"anchor":"","smoothness":"","breakpoint":"Desktop"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"-140","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":[]},"advanceAnimation":{"actions":[],"smoothness":"4","anchor":"guten-90biZS"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-oqLnAO"><div class="guten-column-wrapper" data-id="oqLnAO"><!-- wp:gutenverse/spacer {"elementId":"guten-DBgbP7","space":{"Desktop":{"point":"490","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]}}} -->
<div class="guten-element guten-spacer guten-DBgbP7"></div>
<!-- /wp:gutenverse/spacer -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-47UkHb","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-0"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"0","right":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"18","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"18","right":"0","bottom":"18","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"25","bottom":"25","left":"25"}}}} -->
<div class="section-wrapper" data-id="47UkHb"><section class="wp-block-gutenverse-section guten-element guten-section guten-47UkHb layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-inOhhd","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-inOhhd"><div class="guten-column-wrapper" data-id="inOhhd"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-F0lSRl","alignText":{"Desktop":"center"},"text":"Jhon Doe","focusText":"─ “Etiamn integer maximus fringilla nibh, id sagittis massad efficitur necaurisu.”","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"white"},"mainTypography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"0","bottom":"0"}}},"mainPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"5","top":"0","right":"0","bottom":"0"}}},"focusPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-advanced-heading guten-F0lSRl"><div class="heading-section "><h2 class="heading-title"><span class="heading-title">Jhon Doe</span><span class="heading-focus">─ “Etiamn integer maximus fringilla nibh, id sagittis massad efficitur necaurisu.”</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
