<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Service Gutenverse Services', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-w5vpWA","background":{"videoPlayOnMobile":false,"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(237, 250, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.976"}],"gradientType":"linear"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"170","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"120","right":"20","bottom":"100","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"100","bottom":"40"}}},"zIndex":{"Desktop":"1","Tablet":1},"hideDesktop":false} -->
<div class="section-wrapper" data-id="w5vpWA"><section class="wp-block-gutenverse-section guten-element guten-section guten-w5vpWA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-KiF8gZ","backgroundAnimated":{"actions":[]},"horizontalAlign":{"Desktop":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KiF8gZ"><div class="guten-column-wrapper" data-id="KiF8gZ"><!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-63TrzT","border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"1","color":{"type":"variable","id":"bZzZn0"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"70","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="63TrzT"><section class="wp-block-gutenverse-section guten-element guten-section guten-63TrzT layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"elementId":"guten-CHbrRG","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"flex-start"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CHbrRG"><div class="guten-column-wrapper" data-id="CHbrRG"><!-- wp:gutenverse/heading {"elementId":"guten-Teyneq","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"background":{"type":"default","color":{"r":224,"g":234,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"11","left":"11","top":"6","bottom":"6"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-Teyneq">Our Services</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-Soz11b","textAlign":{"Desktop":"center","Mobile":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"ROsdhu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"64","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"10","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"565","unit":"px"}},"transform":{"rotateZ":{"Desktop":{"point":"","unit":"deg"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-Soz11b">Financial guidance</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-ExkoUH","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"center","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-ExkoUH"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Integer convallis ac ligula non volutpat. Morbi tepo molestieex, siteded amet pharetra nisi sagittis ac. Maecenas facilisis enim et volu</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1380"},"isChild":true,"height":{"Desktop":{"point":"480","unit":"px"},"Tablet":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-yqVIDN","heightControl":"min","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-120","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"-160","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"zIndex":{"Tablet":1},"advanceAnimation":{"actions":[],"smoothness":"2","anchor":"","pin":false},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"1200","unit":"px"}}} -->
<div class="section-wrapper" data-id="yqVIDN"><section class="wp-block-gutenverse-section guten-element guten-section guten-yqVIDN layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":50,"Mobile":100},"elementId":"guten-gj3Qc3","background":{"type":"default","color":{"r":6,"g":6,"b":6,"a":1}},"verticalAlign":{"Desktop":"flex-end","Tablet":"flex-end"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"20"}}}},"borderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"0","left":"0"}}}},"boxShadow":{"vertical":"10","blur":"40","spread":"-10","position":"outline","color":{"r":0,"g":0,"b":0,"a":0.08}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"Detail","delay":true,"defaultSpeed":{"point":"0.05","unit":"s"},"disableDefault":true,"textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"padding":{"unit":"px","dimension":{"top":"40","right":"25","bottom":"40","left":"25"}},"typography":{"type":"variable","id":"gqDfIO","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Mobile":{"unit":"em","point":"1.1"}}},"background":{"type":"default","color":{"type":"variable","id":"YUPZJz"}},"textColor":{"type":"variable","id":"white"}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-gj3Qc3"><div class="guten-column-wrapper" data-id="gj3Qc3"><!-- wp:gutenverse/wrapper {"elementId":"guten-J0A2Zr","positionType":{"Desktop":"static","Tablet":false,"Mobile":false},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-J0A2Zr with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="J0A2Zr"><!-- wp:gutenverse/image {"elementId":"guten-WokXGq","imgSrc":{"media":{"imageId":347,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp","orientation":"landscape"},"medium":{"height":218,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp","height":728,"width":1000,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"340"},"Mobile":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":0},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","top":"","bottom":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"50","left":"50","top":"10"}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":"3"},"transform":{"ease":"","transformOrigin":{"Desktop":""}},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-WokXGq animated guten-element-hide desktop-fadeInUp"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp" height="728" width="1000" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-GkoLj3","margin":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"25","left":"25","bottom":"25"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="section-wrapper" data-id="GkoLj3"><section class="wp-block-gutenverse-section guten-element guten-section guten-GkoLj3 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-NHoFiA","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NHoFiA"><div class="guten-column-wrapper" data-id="NHoFiA"><!-- wp:gutenverse/heading {"elementId":"guten-f3CvqI","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"acrH3M","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.01"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"265","unit":"px"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-f3CvqI">Budget Analysis </h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-pjA6Pn","verticalAlign":"center","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="pjA6Pn"><section class="wp-block-gutenverse-section guten-element guten-section guten-pjA6Pn layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-TkoDO7"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TkoDO7"><div class="guten-column-wrapper" data-id="TkoDO7"><!-- wp:gutenverse/text-editor {"elementId":"guten-vnrUfh","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-vnrUfh"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames aante ipsum primis in faucibus. Nunc nec pellen.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":50,"Mobile":null},"elementId":"guten-vJn5wn","background":{"type":"gradient","gradientColor":[{"color":"rgba(64, 182, 253, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(32, 104, 245, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"opacity":"0.1","backgroundAnimated":{"actions":[]},"verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"flex-start"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"borderResponsive":{"Tablet":{"radius":{"unit":"px","dimension":{"right":"20","left":"0","bottom":"20"}}},"Mobile":{"radius":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"boxShadow":{"vertical":"10","blur":"40","spread":"-10","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","bottom":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mouseMoveEffect":{"enable":false},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"Detail","textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"background":{"type":"default","color":{"type":"variable","id":"white"},"fixed":{"Desktop":false},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(220, 246, 255, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear"},"textColor":{"type":"variable","id":"YUPZJz"},"delay":true,"defaultSpeed":{"point":"0.05","unit":"s"},"disableDefault":true,"padding":{"unit":"px","dimension":{"top":"40","right":"25","bottom":"40","left":"25"}},"typography":{"type":"variable","id":"gqDfIO","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Mobile":{"unit":"em","point":"1.1"}}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vJn5wn"><div class="guten-column-wrapper" data-id="vJn5wn"><!-- wp:gutenverse/wrapper {"elementId":"guten-tQv4CO","positionType":{"Desktop":"static","Tablet":false,"Mobile":false},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"test","textBorder":{"radius":{"Desktop":[]}},"background":{"type":"default","color":{"r":199,"g":22,"b":22,"a":1}},"textColor":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-tQv4CO with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="tQv4CO"><!-- wp:gutenverse/image {"elementId":"guten-SPfj7M","imgSrc":{"media":{"imageId":22,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp","orientation":"landscape"},"medium":{"height":300,"width":267,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp","orientation":"portrait"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp","height":898,"width":800,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"248"},"Mobile":{"point":"204","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Mobile":{"radius":[]},"Tablet":{"radius":[]}},"align":{"Desktop":"center"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":200},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"10"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"advanceAnimation":{"type":"scroll","actions":[],"anchor":"","smoothness":""},"transform":{"ease":"","transformOrigin":{"Desktop":""}},"lazyLoad":true,"className":"guten-data"} -->
<div data-id="SPfj7M" class="wp-block-gutenverse-image guten-element guten-image guten-SPfj7M animated guten-element-hide desktop-fadeInUp guten-data"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp" height="898" width="800" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-odsaBd","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"25","left":"25","bottom":"25"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="section-wrapper" data-id="odsaBd"><section class="wp-block-gutenverse-section guten-element guten-section guten-odsaBd layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":100},"elementId":"guten-Y6YrCM"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Y6YrCM"><div class="guten-column-wrapper" data-id="Y6YrCM"><!-- wp:gutenverse/heading {"elementId":"guten-m2f5cA","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"acrH3M","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.01"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"282","unit":"px"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-m2f5cA">Financial Planning</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-ErjSFP","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":191,"g":29,"b":29,"a":0}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="ErjSFP"><section class="wp-block-gutenverse-section guten-element guten-section guten-ErjSFP layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-I7Xmlk"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-I7Xmlk"><div class="guten-column-wrapper" data-id="I7Xmlk"><!-- wp:gutenverse/text-editor {"elementId":"guten-m1WVyJ","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"left"},"textColor":{"r":255,"g":255,"b":255,"a":0.7},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-m1WVyJ"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames aante ipsum primis in faucibus. Nunc nec pellen.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":100,"Mobile":null},"elementId":"guten-2jfyWR","background":{"type":"gradient","color":{"r":6,"g":6,"b":6,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"backgroundAnimated":{"actions":[]},"verticalAlign":{"Desktop":"flex-end"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"20","left":"0"}}},"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"20"}},"top":{"type":"none"},"left":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}}},"boxShadow":{"color":{"r":83,"g":180,"b":252,"a":0.1},"horizontal":"0","vertical":"3","blur":"30","spread":"4","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"Detail","delay":true,"defaultSpeed":{"point":"0.05","unit":"s"},"disableDefault":true,"textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"textColor":{"type":"variable","id":"white"},"background":{"type":"default","color":{"type":"variable","id":"YUPZJz"}},"padding":{"unit":"px","dimension":{"top":"40","right":"25","bottom":"40","left":"25"}},"typography":{"type":"variable","id":"gqDfIO","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Mobile":{"unit":"em","point":"1.1"}}}},"hideTablet":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-2jfyWR hide-tablet"><div class="guten-column-wrapper" data-id="2jfyWR"><!-- wp:gutenverse/wrapper {"elementId":"guten-awr3Ba","positionType":{"Desktop":"static","Tablet":false,"Mobile":false},"backgroundEffect":{"type":"none"},"border":{"radius":{"Desktop":[]}},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-awr3Ba with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="awr3Ba"><!-- wp:gutenverse/image {"elementId":"guten-Lf6o9I","imgSrc":{"media":{"imageId":16,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp","orientation":"landscape"},"medium":{"height":244,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp","height":487,"width":600,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"250","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":400},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","right":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"advanceAnimation":{"type":"scroll","actions":[],"anchor":"","pin":false,"smoothness":""},"transform":{"ease":"","transformOrigin":{"Desktop":""}},"lazyLoad":true,"className":"guten-data"} -->
<div data-id="Lf6o9I" class="wp-block-gutenverse-image guten-element guten-image guten-Lf6o9I animated guten-element-hide desktop-fadeInUp guten-data"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp" height="487" width="600" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-FGhQ0W","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"25","bottom":"25","left":"25"}}}} -->
<div class="section-wrapper" data-id="FGhQ0W"><section class="wp-block-gutenverse-section guten-element guten-section guten-FGhQ0W layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-OMoA16","margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OMoA16"><div class="guten-column-wrapper" data-id="OMoA16"><!-- wp:gutenverse/heading {"elementId":"guten-PueyjU","type":3,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"acrH3M","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.01"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"left":"","right":""}},"Tablet":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"313","unit":"px"}},"condition":{"filter":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-PueyjU">Tax Optimization</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-EhzK8O","verticalAlign":"center","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="EhzK8O"><section class="wp-block-gutenverse-section guten-element guten-section guten-EhzK8O layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-7lV9P1"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-7lV9P1"><div class="guten-column-wrapper" data-id="7lV9P1"><!-- wp:gutenverse/text-editor {"elementId":"guten-j8U2bw","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-j8U2bw"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames aante ipsum primis in faucibus. Nunc nec culpa pelle.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1440"},"height":{"Desktop":{"point":"600","unit":"px"}},"gap":"no","elementId":"guten-HS31sf","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"zIndex":{"Tablet":0,"Desktop":"0","Mobile":"0"},"hideDesktop":false} -->
<div class="section-wrapper" data-id="HS31sf"><section class="wp-block-gutenverse-section guten-element guten-section guten-HS31sf layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-YlbHgu","border":{"radius":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"20"}}}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YlbHgu"><div class="guten-column-wrapper" data-id="YlbHgu"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-FeTvLm","background":{"type":"default","videoPlayOnMobile":false,"gradientColor":[{"color":"rgba(244, 251, 255, 1)","opacity":1,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.976"}],"gradientType":"linear","image":{"Desktop":{"id":3327,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.png"}},"position":{"Desktop":"custom"},"yposition":{"Desktop":{"point":"11","unit":"px"}},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"21","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"xposition":{"Desktop":{"point":"2","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":2,"offset":"0.465"}],"gradientType":"linear"},"border":{"radius":{"Desktop":[]},"top":{"type":"solid","width":"0","color":{"type":"variable","id":"YUPZJz"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"215","bottom":"130","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"110","right":"30","bottom":"110","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"160","right":"20","bottom":"30","left":"20"}}},"zIndex":{"Tablet":0}} -->
<div class="section-wrapper" data-id="FeTvLm"><section class="wp-block-gutenverse-section guten-element guten-section guten-FeTvLm layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"elementId":"guten-afw43y","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"flex-start"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-afw43y"><div class="guten-column-wrapper" data-id="afw43y"><!-- wp:gutenverse/heading {"elementId":"guten-tyk0Ge","textAlign":{"Desktop":"center","Mobile":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"bTDLqP","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"28","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"transform":"normal","spacing":{"Desktop":"-0.02"},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"50","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default","Mobile":"custom"},"positioningWidth":{"Desktop":{"point":"565","unit":"px"},"Mobile":{"point":"250","unit":"px"}},"transform":{"rotateZ":{"Desktop":{"point":"","unit":"deg"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-tyk0Ge">Our another services</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"855"},"isChild":true,"gap":"no","elementId":"guten-dhUluJ","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="dhUluJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-dhUluJ layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":100},"elementId":"guten-kuu9qt","border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[],"right":{"type":"none"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"30"}},"Tablet":[]},"padding":{"Mobile":[],"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kuu9qt"><div class="guten-column-wrapper" data-id="kuu9qt"><!-- wp:gutenverse/icon-box {"elementId":"guten-pSyteV","separateButtonLink":false,"title":"Investment Planning","titleTag":"h3","description":"Samet utam consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas lorem ipsum dolor sit ullamcorper, seda condim.","icon":"gtn gtn-line-chart-light","iconSize":{"Desktop":"30","Mobile":"20"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Mobile":[]},"iconMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"0"}}},"iconColor":{"type":"variable","id":"theme-3"},"iconBgColor":{"type":"variable","id":"theme-7"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"5","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"HVCKFu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"parentSelector":".guten-pSyteV:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-pSyteV guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-line-chart-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Investment Planning</h3><p class="icon-box-description">Samet utam consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas lorem ipsum dolor sit ullamcorper, seda condim.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-RkVfL0","separateButtonLink":false,"title":"Business Consulting","titleTag":"h3","description":"Consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas ullamcorper, orem ipsum dolor sit amet utam  seda condiment.","icon":"fas fa-comment-dollar","iconSize":{"Desktop":"30","Mobile":"20"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Mobile":[]},"iconMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-3"},"iconBgColor":{"type":"variable","id":"theme-7"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"5","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"HVCKFu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"parentSelector":".guten-RkVfL0:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-RkVfL0 guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-comment-dollar"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Business Consulting</h3><p class="icon-box-description">Consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas ullamcorper, orem ipsum dolor sit amet utam  seda condiment.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":100},"elementId":"guten-6TBqzw","border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[],"right":{"type":"none"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"left":"30"}},"Tablet":[]},"padding":{"Mobile":[],"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-6TBqzw"><div class="guten-column-wrapper" data-id="6TBqzw"><!-- wp:gutenverse/icon-box {"elementId":"guten-Wpcqjh","separateButtonLink":false,"title":"Debt Management","titleTag":"h3","description":"Condimentum orem ipsum dolor sit amet utam consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas ullam.","icon":"fas fa-coins","iconSize":{"Desktop":"30","Mobile":"20"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Tablet":[],"Mobile":[]},"iconMargin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-3"},"iconBgColor":{"type":"variable","id":"theme-7"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"iconBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"5","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"HVCKFu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"parentSelector":".guten-Wpcqjh:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-Wpcqjh guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-coins"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Debt Management</h3><p class="icon-box-description">Condimentum orem ipsum dolor sit amet utam consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas ullam.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-sjLziI","separateButtonLink":false,"title":"Risk Assessment","titleTag":"h3","description":"Lorem ipsum dolor sit amet utam consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas ullamcorpe.","icon":"fas fa-hand-holding-usd","iconSize":{"Desktop":"30","Mobile":"20"},"align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Mobile":[]},"iconMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconColor":{"type":"variable","id":"theme-3"},"iconBgColor":{"type":"variable","id":"theme-7"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"5","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"HVCKFu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal"},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"parentSelector":".guten-sjLziI:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-sjLziI guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="fas fa-hand-holding-usd"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Risk Assessment</h3><p class="icon-box-description">Lorem ipsum dolor sit amet utam consectetur adipiscing elite sedeut roin tempor purus addet tortor egestas ullamcorpe.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
