<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Search Gutenverse Hero', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"height":{"Desktop":{"point":"628.38","unit":"px"}},"gap":"no","elementId":"guten-mmwug9","background":{"type":"default","videoPlayOnMobile":false,"image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"yposition":{"Desktop":{"point":"15","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0.8)","active":true,"opacity":0.8,"id":3,"offset":"0.558"},{"color":"rgba(237, 250, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"topDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"loop":true,"width":{"Desktop":"154"},"height":{"Desktop":"490"}},"bottomDividerAnimated":{"type":"none","loadOn":"pageload","colorMode":"default","pauseOnLeave":true,"width":{"Desktop":"200"},"flip":false,"front":false,"loop":false},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"130","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"110","right":"30","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"25","right":"20","bottom":"0","left":"20"}}},"zIndex":{"Desktop":"3"},"condition":{"filter":[]}} -->
<div class="section-wrapper" data-id="mmwug9"><section class="wp-block-gutenverse-section guten-element guten-section guten-mmwug9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-WGFNSJ","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"default","Tablet":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-WGFNSJ"><div class="guten-column-wrapper" data-id="WGFNSJ"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-zGHD4D","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"20","right":"20"}}}},"boxShadow":{"horizontal":"0","vertical":"3","blur":"30","spread":"4","position":"outline","color":{"r":83,"g":180,"b":252,"a":0.1}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"-90"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-80","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"-45","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="zGHD4D"><section class="wp-block-gutenverse-section guten-element guten-section guten-zGHD4D layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-70A0F9","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-70A0F9"><div class="guten-column-wrapper" data-id="70A0F9"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"150","unit":"px"}},"gap":"no","elementId":"guten-olzrUC","verticalAlign":"flex-end","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20"}}},"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"right":{"color":{"type":"variable","id":"theme-7"},"type":"solid","width":"1"},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"30","bottom":"40","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"30","left":"20"}}}} -->
<div class="section-wrapper" data-id="olzrUC"><section class="wp-block-gutenverse-section guten-element guten-section guten-olzrUC layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"flex-end","elementId":"guten-SkC98c","verticalAlign":{"Desktop":"default","Tablet":"center"},"horizontalAlign":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-SkC98c"><div class="guten-column-wrapper" data-id="SkC98c"><!-- wp:gutenverse/heading {"elementId":"guten-dXr3cn","type":1,"textAlign":{"Desktop":"left","Tablet":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"ROsdhu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"64","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","right":"","top":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"15","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"px","point":"630"},"Tablet":{"point":"638","unit":"px"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-dXr3cn">Search Results</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/search {"elementId":"guten-NPcytk","positioningType":{"Mobile":"full"},"border":{"radius":{"Desktop":[]},"all":{"type":"none"}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputPlaceholder":"","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"inputWidth":{"Desktop":{"point":"375","unit":"px"}},"inputTypography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"r":193,"g":204,"b":255,"a":1}}},"inputBorderFocus":{"radius":{"Desktop":[]}},"inputBgColorNormal":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"inputAreaBoxShadow":{"color":{"r":83,"g":180,"b":252,"a":0.1},"horizontal":0,"vertical":"3","blur":"30","spread":-2},"className":"guten-icon"} -->
<div class="guten-element guten-NPcytk guten-search guten-icon"><form class="gutenverse-search-form"><input type="search" placeholder="" name="s" class="gutenverse-search gutenverse-search-input"/><!-- wp:gutenverse/button {"elementId":"guten-w2hVKq","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":100},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"buttonBackground":{"color":{"type":"variable","id":"theme-3"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"10","left":"0"}}},"all":{"type":"none"}},"buttonBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"11","right":"11","bottom":"11","left":"11"}}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"10","left":"0"}}}},"border":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"8"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gMaaVN","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"weight":"600","transform":"capitalize"},"hoverTextColor":{"type":"variable","id":"white"},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element guten-button-wrapper guten-w2hVKq"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-vCokcT","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":6,"g":6,"b":6,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"20","left":"20","top":"0","right":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"18","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}} -->
<div class="section-wrapper" data-id="vCokcT"><section class="wp-block-gutenverse-section guten-element guten-section guten-vCokcT layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-F5vL2L","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"18","right":"0","bottom":"18","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-F5vL2L"><div class="guten-column-wrapper" data-id="F5vL2L"><!-- wp:gutenverse/spacer {"elementId":"guten-HdvLXv","space":{"Desktop":{"point":"12","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-HdvLXv"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
