<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Home Gutenverse Why Choose Us', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1440"},"height":{"Desktop":{"point":"600","unit":"px"}},"gap":"no","elementId":"guten-AvpjaX","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"zIndex":{"Tablet":0,"Desktop":"0","Mobile":"0"},"hideDesktop":false} -->
<div class="section-wrapper" data-id="AvpjaX"><section class="wp-block-gutenverse-section guten-element guten-section guten-AvpjaX layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-SIg6vo","border":{"radius":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"20"}}}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-SIg6vo"><div class="guten-column-wrapper" data-id="SIg6vo"><!-- wp:gutenverse/section {"width":{"Desktop":"1200","Tablet":"1200"},"isChild":true,"height":{"Desktop":{"point":"282","unit":"px"}},"gap":"no","elementId":"guten-seDFYj","background":{"type":"default","videoPlayOnMobile":false,"gradientColor":[{"color":"rgba(244, 251, 255, 1)","opacity":1,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.976"}],"gradientType":"linear","image":{"Desktop":{"id":441,"image":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/dot-pattern.webp"}},"position":{"Desktop":"custom"},"yposition":{"Desktop":{"point":"11","unit":"px"}},"repeat":{"Desktop":"repeat"},"size":{"Desktop":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"21","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"xposition":{"Desktop":{"point":"2","unit":"px"}}},"backgroundOverlay":{"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":true,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"border":{"radius":{"Desktop":[]},"top":{"type":"solid","width":"0","color":{"type":"variable","id":"YUPZJz"}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"200","bottom":"120","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"110","right":"30","bottom":"0","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"160","right":"20","bottom":"0","left":"20"}}},"zIndex":{"Tablet":0}} -->
<div class="section-wrapper" data-id="seDFYj"><section class="wp-block-gutenverse-section guten-element guten-section guten-seDFYj layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"elementId":"guten-Jdg03L","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Jdg03L"><div class="guten-column-wrapper" data-id="Jdg03L"><!-- wp:gutenverse/text-editor {"elementId":"guten-yythAI","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"25","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hideDesktop":false,"hideMobile":false,"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element gutenverse-text-editor guten-yythAI"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Your Trusted Financial Partner</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1000"},"isChild":true,"gap":"no","elementId":"guten-H5En0v","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"70","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="H5En0v"><section class="wp-block-gutenverse-section guten-element guten-section guten-H5En0v layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":33,"Mobile":50},"elementId":"guten-hSmCUN","border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[],"right":{"type":"none"}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hSmCUN"><div class="guten-column-wrapper" data-id="hSmCUN"><!-- wp:gutenverse/fun-fact {"elementId":"guten-UVAJJn","icon":"","iconBorder":{"radius":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"2","right":"2","bottom":"2","left":"2"}}}},"iconBorderResponsive":{"Mobile":{"radius":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"90","suffix":"%","title":"Profit Growth","numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]}}} -->
<div class="guten-element guten-UVAJJn guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="90" data-duration="3500"></span><span class="suffix">%</span></div><span class="title">Profit Growth</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":"33","Mobile":50},"elementId":"guten-G3RENq"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-G3RENq"><div class="guten-column-wrapper" data-id="G3RENq"><!-- wp:gutenverse/fun-fact {"elementId":"guten-nbHXIE","icon":"","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"prefix":"","number":"24/7","suffix":"","title":"Customer Care","numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[]}} -->
<div class="guten-element guten-nbHXIE guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="24/7" data-duration="3500"></span><span class="suffix"></span></div><span class="title">Customer Care</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":null,"Mobile":50},"elementId":"guten-KbRCqE","horizontalAlign":{"Desktop":"default","Mobile":"default"},"border":{"radius":{"Desktop":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Mobile":[]},"hideTablet":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KbRCqE hide-tablet"><div class="guten-column-wrapper" data-id="KbRCqE"><!-- wp:gutenverse/fun-fact {"elementId":"guten-flTEZr","icon":"","iconColor":{"Mobile":{"type":"variable","id":"CioHMV"}},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"130","suffix":"+","title":"Trusted by Companies","alignButtons":{"Desktop":"center"},"numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="guten-element guten-flTEZr guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="130" data-duration="3500"></span><span class="suffix">+</span></div><span class="title">Trusted by Companies</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":"33","Mobile":50},"elementId":"guten-VyDTAZ","border":{"radius":{"Desktop":[]}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VyDTAZ"><div class="guten-column-wrapper" data-id="VyDTAZ"><!-- wp:gutenverse/fun-fact {"elementId":"guten-HSomHC","icon":"","iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"15","suffix":"K","title":"Happy Client","numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-2"}},"numberTypography":{"type":"variable","id":"WnIbbi","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"titleTypography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"contentPadding":{"Desktop":[]}} -->
<div class="guten-element guten-HSomHC guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class=""></i></div><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="15" data-duration="3500"></span><span class="suffix">K</span></div><span class="title">Happy Client</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
