<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Monify Lite Home Gutenverse Services', 'monify-lite' ),
	'categories' => array( 'monify-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-a4lxbF","background":{"videoPlayOnMobile":false,"type":"gradient","gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(237, 250, 255, 1)","active":false,"opacity":1,"id":2,"offset":"0.976"}],"gradientType":"linear"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"70","right":"20","bottom":"100","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"40","bottom":"40"}}},"zIndex":{"Desktop":"1","Tablet":1},"hideDesktop":false} -->
<div class="section-wrapper" data-id="a4lxbF"><section class="wp-block-gutenverse-section guten-element guten-section guten-a4lxbF layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-9K9PMA","backgroundAnimated":{"actions":[]},"horizontalAlign":{"Desktop":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9K9PMA"><div class="guten-column-wrapper" data-id="9K9PMA"><!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-ZO2s3f","border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"1","color":{"type":"variable","id":"bZzZn0"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"70","top":"0","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="ZO2s3f"><section class="wp-block-gutenverse-section guten-element guten-section guten-ZO2s3f layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":100},"elementId":"guten-d8iJB0","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"flex-start"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-d8iJB0"><div class="guten-column-wrapper" data-id="d8iJB0"><!-- wp:gutenverse/heading {"elementId":"guten-tNGxT4","type":3,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"BzM2Ek","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"capitalize"},"background":{"type":"default","color":{"r":224,"g":234,"b":255,"a":1}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"11","left":"11","top":"6","bottom":"6"}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-tNGxT4">Our Services</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-BwbE7n","textAlign":{"Desktop":"center","Mobile":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"ROsdhu","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"64","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.02"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"10","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"565","unit":"px"}},"transform":{"rotateZ":{"Desktop":{"point":"","unit":"deg"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-BwbE7n">Financial guidance</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-YHphq7","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"center","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"dbSDLn","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"spacing":{"Desktop":"-0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-YHphq7"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Integer convallis ac ligula non volutpat. Morbi tepo molestieex, siteded amet pharetra nisi sagittis ac. Maecenas facilisis enim et volu</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1380"},"isChild":true,"height":{"Desktop":{"point":"480","unit":"px"},"Tablet":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-FWCbGa","heightControl":"min","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"-120","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"-160","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"zIndex":{"Tablet":1},"advanceAnimation":{"actions":[],"smoothness":"2","anchor":"","pin":false},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"1200","unit":"px"}}} -->
<div class="section-wrapper" data-id="FWCbGa"><section class="wp-block-gutenverse-section guten-element guten-section guten-FWCbGa layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":50,"Mobile":100},"elementId":"guten-1DveLR","background":{"type":"default","color":{"r":6,"g":6,"b":6,"a":1}},"verticalAlign":{"Desktop":"flex-end","Tablet":"flex-end"},"horizontalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"20"}}}},"borderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"0","left":"0"}}}},"boxShadow":{"vertical":"10","blur":"40","spread":"-10","position":"outline","color":{"r":0,"g":0,"b":0,"a":0.08}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"Detail","delay":true,"defaultSpeed":{"point":"0.05","unit":"s"},"disableDefault":true,"textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"padding":{"unit":"px","dimension":{"top":"40","right":"25","bottom":"40","left":"25"}},"typography":{"type":"variable","id":"gqDfIO","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Mobile":{"unit":"em","point":"1.1"}}},"background":{"type":"default","color":{"type":"variable","id":"YUPZJz"}},"textColor":{"type":"variable","id":"white"}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1DveLR"><div class="guten-column-wrapper" data-id="1DveLR"><!-- wp:gutenverse/wrapper {"elementId":"guten-9sO4wO","positionType":{"Desktop":"static","Tablet":false,"Mobile":false},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-9sO4wO with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="9sO4wO"><!-- wp:gutenverse/image {"elementId":"guten-UAA86h","imgSrc":{"media":{"imageId":347,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp","orientation":"landscape"},"medium":{"height":218,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp","height":728,"width":1000,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"340"},"Mobile":{"point":"320","unit":"px"},"Tablet":{"point":"","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":0},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":"15"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","top":"","bottom":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"50","left":"50","top":"10"}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":"3"},"transform":{"ease":"","transformOrigin":{"Desktop":""}},"lazyLoad":true} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-UAA86h animated guten-element-hide desktop-fadeInUp"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/money-paper-material-label-brand-bank-1000266-pxhere.com-2.webp" height="728" width="1000" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-Ht1Ock","margin":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"25","left":"25","bottom":"25"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="section-wrapper" data-id="Ht1Ock"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ht1Ock layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-hmFfCL","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hmFfCL"><div class="guten-column-wrapper" data-id="hmFfCL"><!-- wp:gutenverse/heading {"elementId":"guten-AvPcOg","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"acrH3M","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.01"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"265","unit":"px"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-AvPcOg">Budget Analysis </h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-heN6PH","verticalAlign":"center","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="heN6PH"><section class="wp-block-gutenverse-section guten-element guten-section guten-heN6PH layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-kSHkfu"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-kSHkfu"><div class="guten-column-wrapper" data-id="kSHkfu"><!-- wp:gutenverse/text-editor {"elementId":"guten-ycaFMY","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-ycaFMY"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames aante ipsum primis in faucibus. Nunc nec pellen.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":50,"Mobile":null},"elementId":"guten-krhyo6","background":{"type":"gradient","gradientColor":[{"color":"rgba(64, 182, 253, 1)","opacity":1,"active":false,"id":1,"offset":"0.000"},{"color":"rgba(32, 104, 245, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"180"},"opacity":"0.1","backgroundAnimated":{"actions":[]},"verticalAlign":{"Desktop":"flex-end"},"horizontalAlign":{"Desktop":"flex-start"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"borderResponsive":{"Tablet":{"radius":{"unit":"px","dimension":{"right":"20","left":"0","bottom":"20"}}},"Mobile":{"radius":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}},"boxShadow":{"vertical":"10","blur":"40","spread":"-10","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","bottom":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"mouseMoveEffect":{"enable":false},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"Detail","textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"background":{"type":"default","color":{"type":"variable","id":"white"},"fixed":{"Desktop":false},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(220, 246, 255, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear"},"textColor":{"type":"variable","id":"YUPZJz"},"delay":true,"defaultSpeed":{"point":"0.05","unit":"s"},"disableDefault":true,"padding":{"unit":"px","dimension":{"top":"40","right":"25","bottom":"40","left":"25"}},"typography":{"type":"variable","id":"gqDfIO","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Mobile":{"unit":"em","point":"1.1"}}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-krhyo6"><div class="guten-column-wrapper" data-id="krhyo6"><!-- wp:gutenverse/wrapper {"elementId":"guten-CxEeN6","positionType":{"Desktop":"static","Tablet":false,"Mobile":false},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"test","textBorder":{"radius":{"Desktop":[]}},"background":{"type":"default","color":{"r":199,"g":22,"b":22,"a":1}},"textColor":{"r":255,"g":255,"b":255,"a":1}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-CxEeN6 with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="CxEeN6"><!-- wp:gutenverse/image {"elementId":"guten-6Afk2A","imgSrc":{"media":{"imageId":22,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp","orientation":"landscape"},"medium":{"height":300,"width":267,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp","orientation":"portrait"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp","height":898,"width":800,"orientation":"portrait"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"px","point":"248"},"Mobile":{"point":"190","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":200},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"10"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"advanceAnimation":{"type":"scroll","actions":[],"anchor":"","smoothness":""},"transform":{"ease":"","transformOrigin":{"Desktop":""}},"lazyLoad":true,"className":"guten-data"} -->
<div data-id="6Afk2A" class="wp-block-gutenverse-image guten-element guten-image guten-6Afk2A animated guten-element-hide desktop-fadeInUp guten-data"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/StockSnap_M9MYHLGNDA-2.webp" height="898" width="800" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-2n1jdK","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"25","left":"25","bottom":"25"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="section-wrapper" data-id="2n1jdK"><section class="wp-block-gutenverse-section guten-element guten-section guten-2n1jdK layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":100},"elementId":"guten-pbVuBy"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pbVuBy"><div class="guten-column-wrapper" data-id="pbVuBy"><!-- wp:gutenverse/heading {"elementId":"guten-9UCABN","type":3,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"acrH3M","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.01"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"282","unit":"px"}}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-9UCABN">Financial Planning</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-0nISf6","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"r":191,"g":29,"b":29,"a":0}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="0nISf6"><section class="wp-block-gutenverse-section guten-element guten-section guten-0nISf6 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-VBVaGL"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VBVaGL"><div class="guten-column-wrapper" data-id="VBVaGL"><!-- wp:gutenverse/text-editor {"elementId":"guten-347Hn6","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"left"},"textColor":{"r":255,"g":255,"b":255,"a":0.7},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"custom","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-347Hn6"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames aante ipsum primis in faucibus. Nunc nec pellen.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":100,"Mobile":null},"elementId":"guten-xmem3r","background":{"type":"gradient","color":{"r":6,"g":6,"b":6,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","opacity":1,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"backgroundAnimated":{"actions":[]},"verticalAlign":{"Desktop":"flex-end"},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"20","left":"0"}}},"top":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"right":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}},"bottom":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-7"}}},"borderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"20"}},"top":{"type":"none"},"left":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-7"}}}},"boxShadow":{"color":{"r":83,"g":180,"b":252,"a":0.1},"horizontal":"0","vertical":"3","blur":"30","spread":"4","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"cursorEffect":{"defaultStyle":"style1","type":"text","show":false,"text":"Detail","delay":true,"defaultSpeed":{"point":"0.05","unit":"s"},"disableDefault":true,"textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"textColor":{"type":"variable","id":"white"},"background":{"type":"default","color":{"type":"variable","id":"YUPZJz"}},"padding":{"unit":"px","dimension":{"top":"40","right":"25","bottom":"40","left":"25"}},"typography":{"type":"variable","id":"gqDfIO","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.1"},"Mobile":{"unit":"em","point":"1.1"}}}},"hideTablet":true} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xmem3r hide-tablet"><div class="guten-column-wrapper" data-id="xmem3r"><!-- wp:gutenverse/wrapper {"elementId":"guten-H1wour","positionType":{"Desktop":"static","Tablet":false,"Mobile":false},"backgroundEffect":{"type":"none"},"border":{"radius":{"Desktop":[]}},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-H1wour with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="H1wour"><!-- wp:gutenverse/image {"elementId":"guten-DB5Khv","imgSrc":{"media":{"imageId":16,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp","orientation":"landscape"},"medium":{"height":244,"width":300,"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp","orientation":"landscape"},"full":{"url":"' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp","height":487,"width":600,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"","captionOriginal":"","width":{"Desktop":{"unit":"%","point":""},"Mobile":{"point":"260","unit":"px"}},"imgBorder":{"radius":{"Desktop":[]}},"imgBorderResponsive":{"Mobile":{"radius":[]}},"align":{"Desktop":"center"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":400},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","right":"0","top":"0","bottom":"0"}},"Mobile":[]},"advanceAnimation":{"type":"scroll","actions":[],"anchor":"","pin":false,"smoothness":""},"transform":{"ease":"","transformOrigin":{"Desktop":""}},"lazyLoad":true,"className":"guten-data"} -->
<div data-id="DB5Khv" class="wp-block-gutenverse-image guten-element guten-image guten-DB5Khv animated guten-element-hide desktop-fadeInUp guten-data"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( MONIFY_LITE_URI ) . 'assets/img/0508173-2590-FCBD-5A294622716E1CCE.webp" height="487" width="600" alt="" loading="lazy"/></div></div>
<!-- /wp:gutenverse/image -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"gap":"no","elementId":"guten-MLTjsG","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"25","bottom":"25","left":"25"}}}} -->
<div class="section-wrapper" data-id="MLTjsG"><section class="wp-block-gutenverse-section guten-element guten-section guten-MLTjsG layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-eqmHcJ","margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eqmHcJ"><div class="guten-column-wrapper" data-id="eqmHcJ"><!-- wp:gutenverse/heading {"elementId":"guten-xSItXX","type":3,"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"acrH3M","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600","transform":"normal","spacing":{"Desktop":"-0.01"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}},"Desktop":[]},"padding":{"Mobile":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Desktop":{"unit":"px","dimension":{"left":"","right":""}},"Tablet":[]},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"313","unit":"px"}},"condition":{"filter":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-xSItXX">Tax Optimization</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-PeHMhD","verticalAlign":"center","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="PeHMhD"><section class="wp-block-gutenverse-section guten-element guten-section guten-PeHMhD layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-vbTPma"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vbTPma"><div class="guten-column-wrapper" data-id="vbTPma"><!-- wp:gutenverse/text-editor {"elementId":"guten-oBgwkD","gap":{"Mobile":{"point":"","unit":"px"}},"alignment":{"Desktop":"left","Mobile":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"yDZyjD","font":{"label":"Inter","value":"Inter","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"582","unit":"px"},"Mobile":{"point":"","unit":"px"}},"positioningAlign":{"Desktop":"flex-end","Mobile":"flex-start"}} -->
<div class="guten-element gutenverse-text-editor guten-oBgwkD"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Interdum et malesuada fames aante ipsum primis in faucibus. Nunc nec culpa pelle.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
